name: ngatia_sales_app

description: Ngatia Harun Sales & Consultancy Flutter App for online selling and lending services.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  provider: ^6.1.2
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.5
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
